# Generated by Django 2.0.5 on 2018-08-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutridelta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='retinol',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
