# Generated by Django 2.1.1 on 2018-09-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutridelta', '0002_aliment_retinol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliment',
            name='retinol',
        ),
        migrations.AddField(
            model_name='aliment',
            name='frequency',
            field=models.CharField(default='', max_length=200),
        ),
    ]
