# Generated by Django 2.0.5 on 2018-06-16 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180616_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
